// ============================================================================
// SCRIPT GENERATOR - Convert Agent Logs to Puppeteer Script
// ============================================================================
// This module generates the final healed Puppeteer script from the agent execution logs
// The output script uses the "Golden State" selectors that were verified to work
// ============================================================================

import type { StepLog } from "./index";

// ============================================================================
// TYPES
// ============================================================================

export interface ScriptGenerationOptions {
  includeBrowser: boolean; // Include browser launch/close
  includeComments: boolean; // Add descriptive comments
  includeWaits: boolean; // Add wait statements between actions
  headless: boolean; // Run in headless mode
  slowMo: number; // Slow down actions (ms)
  timeout: number; // Page timeout
}

export const DEFAULT_OPTIONS: ScriptGenerationOptions = {
  includeBrowser: true,
  includeComments: true,
  includeWaits: true,
  headless: false,
  slowMo: 100,
  timeout: 30000,
};

// ============================================================================
// SCRIPT GENERATION
// ============================================================================

/**
 * Generate a final Puppeteer script from agent execution logs
 * This is the "Self-Healing Script Generator" output
 */
export function generateFinalScript(
  testName: string,
  startUrl: string,
  logs: StepLog[],
  options: ScriptGenerationOptions = DEFAULT_OPTIONS
): string {
  const lines: string[] = [];

  // Header comment
  if (options.includeComments) {
    lines.push("// ============================================================================");
    lines.push(`// ${testName} - Auto-Healed Test Script`);
    lines.push("// Generated by AI-Powered Self-Healing Test Automation");
    lines.push(`// Generated at: ${new Date().toISOString()}`);
    lines.push("// ============================================================================");
    lines.push("");
  }

  // Imports
  lines.push("const puppeteer = require('puppeteer');");
  lines.push("");

  // Main function
  lines.push("(async () => {");

  // Browser setup
  if (options.includeBrowser) {
    if (options.includeComments) {
      lines.push("  // Launch browser");
    }
    lines.push("  const browser = await puppeteer.launch({");
    lines.push(`    headless: ${options.headless},`);
    lines.push(`    slowMo: ${options.slowMo},`);
    lines.push("  });");
    lines.push("");
    lines.push("  const page = await browser.newPage();");
    lines.push(`  page.setDefaultTimeout(${options.timeout});`);
    lines.push("");
  }

  // Navigation
  if (options.includeComments) {
    lines.push("  // Navigate to start URL");
  }
  lines.push(`  await page.goto('${startUrl}', { waitUntil: 'networkidle0' });`);
  
  if (options.includeWaits) {
    lines.push("  await page.waitForTimeout(1000);");
  }
  lines.push("");

  // Process each successful step
  const successfulSteps = logs.filter(log => 
    log.action && log.result?.success && log.selectorUsed
  );

  for (let i = 0; i < successfulSteps.length; i++) {
    const log = successfulSteps[i];
    const action = log.action!;
    const selector = log.selectorUsed!;
    const selectorType = log.selectorType || "css";

    if (options.includeComments) {
      lines.push(`  // Step ${log.stepNumber}: ${action.description}`);
      
      if (log.healing.successful) {
        lines.push(`  // ✅ This selector was auto-healed during execution`);
      }
    }

    // Generate action code based on type
    const selectorString = selectorType === "xpath" 
      ? `::-p-xpath(${selector})`
      : selector;

    switch (action.type) {
      case "click":
        lines.push(`  await page.waitForSelector('${selectorString}');`);
        lines.push(`  await page.click('${selectorString}');`);
        break;

      case "type":
        lines.push(`  await page.waitForSelector('${selectorString}');`);
        lines.push(`  await page.type('${selectorString}', '${escapeString(action.value || "")}');`);
        break;

      case "select":
        lines.push(`  await page.waitForSelector('${selectorString}');`);
        lines.push(`  await page.select('${selectorString}', '${escapeString(action.value || "")}');`);
        break;

      case "navigate":
        lines.push(`  await page.goto('${action.value}', { waitUntil: 'networkidle0' });`);
        break;

      case "verify":
        lines.push(`  await page.waitForSelector('${selectorString}');`);
        lines.push(`  console.log('✅ Element verified: ${action.description}');`);
        break;

      case "wait":
        lines.push(`  await page.waitForSelector('${selectorString}');`);
        break;

      default:
        if (options.includeComments) {
          lines.push(`  // Unknown action type: ${action.type}`);
        }
    }

    // Add wait between actions
    if (options.includeWaits && i < successfulSteps.length - 1) {
      lines.push("  await page.waitForTimeout(500);");
    }

    lines.push("");
  }

  // Browser cleanup
  if (options.includeBrowser) {
    if (options.includeComments) {
      lines.push("  // Close browser");
    }
    lines.push("  await browser.close();");
    lines.push("");
    lines.push("  console.log('✅ Test completed successfully');");
  }

  // Error handling
  lines.push("})().catch(error => {");
  lines.push("  console.error('❌ Test failed:', error);");
  lines.push("  process.exit(1);");
  lines.push("});");

  return lines.join("\n");
}

/**
 * Generate a more advanced script with error handling and screenshots
 */
export function generateAdvancedScript(
  testName: string,
  startUrl: string,
  logs: StepLog[],
  options: ScriptGenerationOptions = DEFAULT_OPTIONS
): string {
  const lines: string[] = [];

  // Header
  if (options.includeComments) {
    lines.push("// ============================================================================");
    lines.push(`// ${testName} - Advanced Auto-Healed Test Script`);
    lines.push("// Includes error handling, screenshots, and detailed logging");
    lines.push(`// Generated at: ${new Date().toISOString()}`);
    lines.push("// ============================================================================");
    lines.push("");
  }

  // Imports
  lines.push("const puppeteer = require('puppeteer');");
  lines.push("const fs = require('fs');");
  lines.push("const path = require('path');");
  lines.push("");

  // Helper functions
  lines.push("// Helper: Take screenshot on error");
  lines.push("async function takeScreenshot(page, stepName) {");
  lines.push("  const screenshotDir = path.join(__dirname, 'screenshots');");
  lines.push("  if (!fs.existsSync(screenshotDir)) {");
  lines.push("    fs.mkdirSync(screenshotDir, { recursive: true });");
  lines.push("  }");
  lines.push("  const filename = `${testName.replace(/\\s+/g, '_')}_${stepName}_${Date.now()}.png`;");
  lines.push("  await page.screenshot({ path: path.join(screenshotDir, filename), fullPage: true });");
  lines.push("  console.log(`📸 Screenshot saved: ${filename}`);");
  lines.push("}");
  lines.push("");

  // Main function
  lines.push("(async () => {");
  lines.push("  let browser;");
  lines.push("  let page;");
  lines.push("");
  lines.push("  try {");

  // Browser setup
  if (options.includeBrowser) {
    lines.push("    console.log('🚀 Launching browser...');");
    lines.push("    browser = await puppeteer.launch({");
    lines.push(`      headless: ${options.headless},`);
    lines.push(`      slowMo: ${options.slowMo},`);
    lines.push("    });");
    lines.push("");
    lines.push("    page = await browser.newPage();");
    lines.push(`    page.setDefaultTimeout(${options.timeout});`);
    lines.push("");
  }

  // Navigation
  lines.push(`    console.log('🌐 Navigating to ${startUrl}...');`);
  lines.push(`    await page.goto('${startUrl}', { waitUntil: 'networkidle0' });`);
  
  if (options.includeWaits) {
    lines.push("    await page.waitForTimeout(1000);");
  }
  lines.push("");

  // Process steps
  const successfulSteps = logs.filter(log => 
    log.action && log.result?.success && log.selectorUsed
  );

  for (const log of successfulSteps) {
    const action = log.action!;
    const selector = log.selectorUsed!;
    const selectorType = log.selectorType || "css";

    lines.push(`    console.log('📍 Step ${log.stepNumber}: ${action.description}');`);
    
    const selectorString = selectorType === "xpath" 
      ? `::-p-xpath(${selector})`
      : selector;

    switch (action.type) {
      case "click":
        lines.push(`    await page.waitForSelector('${selectorString}');`);
        lines.push(`    await page.click('${selectorString}');`);
        break;

      case "type":
        lines.push(`    await page.waitForSelector('${selectorString}');`);
        lines.push(`    await page.type('${selectorString}', '${escapeString(action.value || "")}');`);
        break;

      case "select":
        lines.push(`    await page.waitForSelector('${selectorString}');`);
        lines.push(`    await page.select('${selectorString}', '${escapeString(action.value || "")}');`);
        break;

      case "navigate":
        lines.push(`    await page.goto('${action.value}', { waitUntil: 'networkidle0' });`);
        break;

      case "verify":
        lines.push(`    await page.waitForSelector('${selectorString}');`);
        lines.push(`    console.log('✅ Element verified');`);
        break;

      case "wait":
        lines.push(`    await page.waitForSelector('${selectorString}');`);
        break;
    }

    if (options.includeWaits) {
      lines.push("    await page.waitForTimeout(500);");
    }
    lines.push("");
  }

  // Success
  lines.push("    console.log('✅ All steps completed successfully');");
  lines.push("");

  // Cleanup
  if (options.includeBrowser) {
    lines.push("  } catch (error) {");
    lines.push("    console.error('❌ Test failed:', error.message);");
    lines.push("    if (page) {");
    lines.push("      await takeScreenshot(page, 'error');");
    lines.push("    }");
    lines.push("    throw error;");
    lines.push("  } finally {");
    lines.push("    if (browser) {");
    lines.push("      await browser.close();");
    lines.push("    }");
    lines.push("  }");
  }

  lines.push("})();");

  return lines.join("\n");
}

/**
 * Escape special characters in strings for JavaScript
 */
function escapeString(str: string): string {
  return str
    .replace(/\\/g, "\\\\")
    .replace(/'/g, "\\'")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t");
}

/**
 * Generate script statistics
 */
export function generateScriptStats(logs: StepLog[]): {
  totalSteps: number;
  successfulSteps: number;
  healedSteps: number;
  healingRate: number;
} {
  const successfulSteps = logs.filter(log => log.action && log.result?.success);
  const healedSteps = logs.filter(log => log.healing.successful);

  return {
    totalSteps: logs.filter(log => log.action).length,
    successfulSteps: successfulSteps.length,
    healedSteps: healedSteps.length,
    healingRate: successfulSteps.length > 0 
      ? healedSteps.length / successfulSteps.length 
      : 0,
  };
}
